from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path(
        'sign-in/',
        views.SignInView.as_view(),
        name='sign-in'
    ),
    path(
        'sign-out/',
        views.SignOutView.as_view(),
        name='sign-out'
    ),
    re_path(
        r'^monitorear/(?P<id_invernadero>[0-9]+)/',
        views.monitorear_invernadero,
        name = 'monitorear'
    ),
    path(
        'monitorear/',
        views.monitorear_invernadero,
        name = 'monitorear'
    ),
    path(
        '',
        views.InvernaderosListView.as_view(),
        name='invernaderos'
    ),
    path(
        'cultivos/',
        views.CultivosListView.as_view(),
        name='cultivos'
    ),
    path(
        'dispositivos/',
        views.DispositivosListView.as_view(),
        name='dispositivos'
    ),
    path(
        'parametros/',
        views.ParametrosListView.as_view(),
        name='parametros'
    ),
    path(
        'sensores/',
        views.SensoresListView.as_view(),
        name='sensores'
    ),
    path(
        'actuadores/',
        views.ActuadoresListView.as_view(),
        name='actuadores'
    ),
    path(
        'ajax/invernadero/',
        views.invernadero,
        name='ajax-invernadero'
    ),
    path(
        'ajax/dispositivo/',
        views.dispositivo,
        name='ajax-dispositivo'
    ),
    path(
        'ajax/sensor/',
        views.sensor,
        name='ajax-sensor'
    ),
    path(
        'ajax/actuador/',
        views.actuador,
        name='ajax-actuador'
    ),
    path(
        'ajax/cultivo/',
        views.cultivo,
        name='ajax-cultivo'
    ),
    path(
        'ajax/parametro/',
        views.parametro,
        name='ajax-parametro'
    ),
    path(
        'perfil/<slug:pk>/',
        views.PerfilUpdateView.as_view(),
        name='perfil'
    )
]
