# Generated by Django 2.1.2 on 2018-11-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0007_auto_20181105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuador',
            name='is_use',
            field=models.BooleanField(default=False, verbose_name='¿Está siendo usado?'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='is_use',
            field=models.BooleanField(default=False, verbose_name='¿Está siendo usado?'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el dispositivo que se asociará a este actuador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nombre_cultivo',
            field=models.CharField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Seleccione el nombre de la planta a cultivar', max_length=45, null=True, verbose_name='Nombre del cultivo'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el dispositivo que controla este invernadero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el invernadero al que se le realizó la medición', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el dispositivo asociado a este sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Seleccione el invernadero al que se asignará este sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
    ]
