# Generated by Django 2.0 on 2018-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0008_auto_20181107_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='is_activo',
            field=models.BooleanField(default=False, error_messages={'value': 'Debe ser un atributo boleano'}, help_text='Respuesta del dispositivo', verbose_name='¿Está activo?'),
        ),
    ]
