# Generated by Django 2.0 on 2018-11-20 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0009_auto_20181120_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='magnitud_referencia',
            field=models.DecimalField(decimal_places=2, error_messages={'value': 'Ese valor debe ser positivo'}, help_text='Ingrese el valor de la magnitud de referencia para este parámetro', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Magnitud del Parámetro Base'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='nombre_parametro',
            field=models.CharField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Ingrese el nombre del parámetro a medir', max_length=50, null=True, verbose_name='Nombre del parámetro'),
        ),
    ]
